/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComposersIndexRouteImport } from './routes/composers.index'
import { Route as ComposersSlugRouteImport } from './routes/composers.$slug'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposersIndexRoute = ComposersIndexRouteImport.update({
  id: '/composers/',
  path: '/composers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposersSlugRoute = ComposersSlugRouteImport.update({
  id: '/composers/$slug',
  path: '/composers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/composers/$slug': typeof ComposersSlugRoute
  '/composers/': typeof ComposersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/composers/$slug': typeof ComposersSlugRoute
  '/composers': typeof ComposersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/composers/$slug': typeof ComposersSlugRoute
  '/composers/': typeof ComposersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/composers/$slug' | '/composers/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/composers/$slug' | '/composers'
  id: '__root__' | '/' | '/about' | '/composers/$slug' | '/composers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ComposersSlugRoute: typeof ComposersSlugRoute
  ComposersIndexRoute: typeof ComposersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/composers/': {
      id: '/composers/'
      path: '/composers'
      fullPath: '/composers/'
      preLoaderRoute: typeof ComposersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/composers/$slug': {
      id: '/composers/$slug'
      path: '/composers/$slug'
      fullPath: '/composers/$slug'
      preLoaderRoute: typeof ComposersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ComposersSlugRoute: ComposersSlugRoute,
  ComposersIndexRoute: ComposersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
